#baseURL = 'https://justinkwright.github.io/shlbc_website/'
baseURL = 'https://shepherdshilllanebaptistchurch.com/'
languageCode = 'en-us'
title = 'Shepherds Hill Lane Baptist Church'
theme = 'alpha-church'

rssLimit = 5
pagination.pagerSize = 4

enableEmoji = true

# Enter your tracking code to enable Google Analytics
[services]
  [services.googleAnalytics]
    ID = ""

[security]
  enableInlineShortcodes = true

  [security.funcs]
    getenv = ['^HUGO_','^API_KEY_NAME$', '^CI$', '^USER$', '^HOME$']

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  tag = "tags"
  preacher = "preachers"
  series = "series"

#This theme can generate a multi-level menu.
#Use weight= to specify the order of menu items, and parent= to create a submenu item.
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

  [[menu.main]]
    name = "About Us"
    parent = "About"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Leaders"
    parent = "About"
    url = "/leaders"
    weight = 2

  [[menu.main]]
    name = "Youth"
    parent = "About"
    url = "/youth"
    weight = 3

  [[menu.main]]
    name = "Children"
    parent = "About"
    url = "/children"
    weight = 4

  [[menu.main]]
    name = "Giving"
    url = "/giving"
    weight = 4

  # [[menu.main]]
  #   name = "Resources"
  #   url = "#"
  #   weight = 3

  # [[menu.main]]
  #   name = "Youth"
  #   parent = "Resources"
  #   url = "/youth"
  #   weight = 1

  #   [[menu.main]]
  #   name = "Children"
  #   parent = "Resources"
  #   url = "/children"
  #   weight = 2

  # [[menu.main]]
  #   name = "Sermons"
  #   url = "/sermons"
  #   parent = "Resources"
  #   weight = 1

  # [[menu.main]]
  #   name = "Preachers"
  #   url = "/preachers"
  #   parent = "Sermons"
  #   weight = 1

  # [[menu.main]]
  #   name = "Best Ever"
  #   url = "#"
  #   parent = "Sermons"
  #   weight = 1

  # [[menu.main]]
  #   name = "Blog"
  #   url = "/posts"
  #   parent = "Resources"
  #   weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 5

# Paramaters for the whole site
[params]
  title = "Shepherds Hill Lane Baptist Church"
  subtitle = "God is Good All the Time....... All the Time God is Good"
#   logo2 = "img/shlbc_hrz_blk.png"
  keywords = ["theme", "hugo", "podcast"]
  languageCode = "en" # For accessibility this needs to be set. You can find all language codes at https://www.w3schools.com/tags/ref_language_codes.asp
  # bible_popups = "faithlife" #faithlife, blb
  bible_version = "KJV" #HCSB, NIV, NLT, ESV, CSB, etc.
  bible_popups = "blb" #"faithlife" #faithlife, blb
  # bible_version = "KJV1900" #"CSB" #HCSB, NIV, NLT, ESV, etc.
  instant_page = true
#   customCSS = ["example.css"]
#customCSS = ["/css/my.css"]
  # test_api = "{{ getenv 'HUGO_GOOGLE_API' }}"


  [params.author]
    name = "Web Author"
    email = "test@example.com"

  [params.favicon]
    sml = "/example16.png"
    med = "/example32.png"
    #lge = "example96.png"

  [params.banner]
    # image = "img/banner.jpg"
    # image = "images/cross-on-hill.jpeg"
    image = "img/shlc-banner.png"

#  [params.style]
#    googleFonts = ["Cardo", "Crimson+Text", "Merriweather", "Playfair+Display:400,700", "Roboto+Slab"]

  [params.podcast]
    title = "Listen to Alpha Church"
    summary = "Alpha-Church sermons, talks, messages—podcasted."
    copyright = "The files in the podcast are in the public domain."
    image = "img/podcast-cover.jpg"
    category = "Religion & Spirituality"
    sub_category = "Christianity"
    iTunes = "https://itunes.apple.com/us/podcast/tgc-word-of-the-week/id1034013280"
    feed = "https://www.thegospelcoalition.org/podcasts/word-of-the-week/feed/?feed=podcast"
    spotify = "https://open.spotify.com/show/1iE3aJkf8fJ2FVTvJGFd4h"

  [params.map]
    #service = "osm" #"osm" for OpenStreetMaps, "google" for Google Maps, or "mapbox" for Mapbox, see SETUP.md
    # For Open Street Map widgets
    latitude = "33.304038788294605"
    longitude = "-96.26261624627612"
    zoom = "15"
    # If you want to use google maps you'll need an API Key from Google https://developers.google.com/maps/documentation/embed/get-api-key
     service = "google"
    api_key = "{{ getenv 'HUGO_GOOGLE_API' }}"
    #language = "fr" #Optional
    #region = "FR" #Optional
    api_test = "{{ getenv API_KEY_NAME }}"
    # api_test = "thisisatest"
    # test_api = "{{ getenv 'HUGO_GOOGLE_API' }}"

  [params.contact]
    #Use this section to automate contact form.
    #Set service to either "netlify", "formspree" or "php"
    #For formspree, please setup an account at https://formspree.io/
    #For netlify, please read https://www.netlify.com/docs/form-handling/
    #
    #If you use netlify, you'll need to set the confirm_page value (otherwise users will see a generic netlify response)
    #If you use formspree, you'll need to set your formspree form_id.
    #
    #If you use php, you need to host this site on a Server capable of running php.
    # Please edit the /static/contact_mail.php file from the exampleSite.
    service = "google" #or "formspree" or "php"
    confirm_page = "/contact_thanks" #only used by netlify
    name = 'entry.2005620554'
    email = 'entry.1045781291'
    phone_number = 'entry.1166974658'
    message = 'entry.839337160'
    #action = ''
    action = "https://docs.google.com/forms/u/0/d/e/1FAIpQLSfR6KDDARfDlgGCxHBkY3BOjrBHXtzD8bepWJXXmU9A8GaqzQ/formResponse"

# <input type="hidden" name="entry.2005620554" value="">
# <input type="hidden" name="entry.1045781291" value="">
# <input type="hidden" name="entry.1166974658" value="">
# <input type="hidden" name="entry.839337160" value="">



    # phone = "true"
    # text = "text?"
    # formspree_formid="" #only used by formspree


    [params.footer]
    #   copyright = ["[CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)",
    #                "Design: [HTML5 UP](//html5up.net/alpha)",
    #                "[Hugo Port](//gohugo.io) by [Daniel Saunders](//github.com/funkydan2)"
    #               ]

      copyright = ["© Shepherd Hill Lane Baptist Church",
                #    "Built with: [hugo](https://gohugo.io)",
                   "Design: [HTML5 UP](//html5up.net/alpha)",
                   "[Hugo Port](//gohugo.io) by [Daniel Saunders](//github.com/funkydan2)"
                  ]

    # [[params.links]]
    #   service = "Twitter"
    #   icon = "fa-twitter"
    #   icon_pack = "fab"
    #   link = "//twitter.com/"

    [[params.links]]
      service = "Facebook"
      icon = "fa-facebook"
      icon_pack = "fab"
      link = "//facebook.com/shepherdshilllane"

    # [[params.links]]
    #   service = "Podcast"
    #   icon = "fa-podcast"
    #   icon_pack = "fas"
    #   link = "/sermons/index.xml"

    [[params.links]]
      service = "Instagram"
      icon = "fa-instagram"
      icon_pack = "fab"
      link = "//instagram.com/shlbchurch"

    [[params.links]]
      service = "YouTube"
      icon = "fa-youtube"
      icon_pack = "fab"
      link = "//youtube.com/@Shepherdshilllanebaptistchurch"

    # [[params.links]]
    #   service = "Full RSS Feed"
    #   icon = "fa-rss"
    #   icon_pack = "fas"
    #   link = "/index.xml"
